apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJhc2h3a2VubnkiLCJwYXNzd29yZCI6IkFzaHdpbmRta0AyMDI2IiwiZW1haWwiOiJhc2h3aW5rZW5ueWFrMjU3QGdtYWlsLmNvbSIsImF1dGgiOiJZWE5vZDJ0bGJtNTVPa0Z6YUhkcGJtUnRhMEF5TURJMiJ9fX0=
kind: Secret
metadata:
  name: dockerhub-secret
type: kubernetes.io/dockerconfigjson
